######################################################
##      _                _                  _       ##
##     | |              | |                | |      ##
##   __| | ___  ___ __ _| |_ ___  _ __ ___ | |__    ##
##  / _` |/ _ \/ __/ _` | __/ _ \| '_ ` _ \| '_ \   ##
## | (_| |  __/ (_| (_| | || (_) | | | | | | |_) |  ##
##  \__,_|\___|\___\__,_|\__\___/|_| |_| |_|_.__/   ##
##                                                  ##
######################################################                                               

# For more information see: https://github.com/shandley/decatomb
# Written by: Scott Handley (handley.scott@gmail.com), March 2021

---
##################
# Run Parameters #
##################

Paths:
  # The base database directory
 
  Databases: /mnt/data3/shandley/dev/decatomb_db
  
  # The reads directory has your input fastq files
  # Note: All of your results will go into this directory

  Reads: /mnt/data3/shandley/hecatomb_runs/test_data
  
  # Where do you want the results stored?
  # Recommended that you make a specific based dir (e.g. heactomb_runs) followed by project specific (e.g. test_data) for all of your runs
  #This should not be a subdirectory to where your Reads are located!
  
  Results: test_data_results
  
  # Host directory name
  # e.g. human, mouse, dog, etc.
  # Needs to be the name of the directory containing the masked reference
  # If your reference is not available post an issue on GitHub requesting it to be added

  Host: macaque

  # Temp is a temporary directory. By default we make 
  # subdirectories in here for each application

  Temp: .tmp

System:
  # How much memory you want to allocate to java (required for bbtools steps)
  
  # This is in gigabytes of memory (e.g 2GB would use 2, 128GB would use 128)
  
  Memory: 48
  
  # Number of threads to use
  
  Threads: 24

############################
# Optional Rule Parameters #                  
############################
### Tuning parameters
### Advise not to change and keep default, but included here for fine-tuning to ones own dataset
### See documentation for each individual program for detailed explanation (ie. for QSCORE review the bbduk.sh manual)

## Preprocessing
QSCORE: 15 # Read quality trimming score (rule remove_low_quality in 00_preprocessing.smk)
READ_MINLENGTH: 100 # Minimum read length during QC steps (rule remove_low_quality in 00_preprocessing.smk)
CONTIG_MINLENGTH: 1000 # Read minimum length (rule contig_reformating_and_stats in 00_preprocessing.smk)
ENTROPY: 0.7 # Read minimum entropy (rule remove_low_quality in 00_preprocessing.smk)